=== CBIIT/cadsr-sentinel/sentinel/dtd/cadsrsentinel-1.0.dtd
<!-- Copyright ScenPro, Inc 2007

    $Header: /share/content/gforge/sentinel/sentinel/dtd/cadsrsentinel-1.0.dtd,v 1.2 2007-12-06 20:52:09 hebell Exp $
    $Name: not supported by cvs2svn $
-->
<!ELEMENT cadsr (alertReport* | pragma*)>
<!ELEMENT alertReport (database | definition | changedItem* | associateItem* | group* | pragma*)>
<!ATTLIST alertReport
    version CDATA #FIXED "1.0"
    softwareName CDATA #REQUIRED
    softwareVersion CDATA #REQUIRED
>
<!ELEMENT pragma ANY>
<!ATTLIST pragma
    owner CDATA #REQUIRED
>
<!ELEMENT database EMPTY>
<!ATTLIST database
    name CDATA #REQUIRED
    rai CDATA #REQUIRED
    server CDATA #REQUIRED
>
<!ELEMENT definition (name | id | intro? | createdBy | recipient+ | summary? | lastAutoRun? | frequency | status | level | start | end | createdOn | criteria* | monitor*)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT intro (#PCDATA)>
<!ELEMENT name EMPTY>
<!ATTLIST name
    value CDATA #REQUIRED
>
<!ELEMENT createdBy EMPTY>
<!ATTLIST createdBy
    user CDATA #REQUIRED
    name CDATA #REQUIRED
    email CDATA #REQUIRED
>
<!ELEMENT recipient EMPTY>
<!ATTLIST recipient
    user CDATA #IMPLIED
    name CDATA #IMPLIED
    email CDATA #IMPLIED
    url CDATA #IMPLIED
>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT criteria (value*)>
<!ATTLIST criteria
    type (CONTEXT | FORM | PROTOCOL | CS | CSI | CREATOR | MODIFIER | REG_STATUS | AC_STATUS | ACTYPE | DATEFILTER) #REQUIRED
    value CDATA #IMPLIED
>
<!ELEMENT value (#PCDATA)>
<!ELEMENT monitor EMPTY>
<!ATTLIST monitor
    type (AC_STATUS | REG_STATUS | VERSION) #REQUIRED
    value CDATA #IMPLIED
>
<!ELEMENT lastAutoRun EMPTY>
<!ATTLIST lastAutoRun
    time CDATA #REQUIRED
>
<!ELEMENT frequency EMPTY>
<!ATTLIST frequency
    unit (Day | Week | Month) #REQUIRED
    value CDATA #IMPLIED
>
<!ELEMENT status EMPTY>
<!ATTLIST status
    code (Active | Once | Range | Inactive) #REQUIRED
    beginDate CDATA #IMPLIED
    endDate CDATA #IMPLIED
>
<!ELEMENT level EMPTY>
<!ATTLIST level
    depth CDATA #REQUIRED
>
<!ELEMENT start EMPTY>
<!ATTLIST start
    date CDATA #REQUIRED
>
<!ELEMENT end EMPTY>
<!ATTLIST end
    date CDATA #REQUIRED
>
<!ELEMENT createdOn EMPTY>
<!ATTLIST createdOn
    time CDATA #REQUIRED
>
<!ELEMENT changedItem (details*)>
<!ATTLIST changedItem
    type (cd | con | conte | cs | csi | de | dec | oc | prop | proto | pv | qc | qcm | qcq | qcv | vd | vm) #REQUIRED
    name CDATA #REQUIRED
    id  ID #REQUIRED
    publicId CDATA #IMPLIED
    version CDATA #IMPLIED
    modifiedByUser CDATA #IMPLIED
    modifiedByName CDATA #IMPLIED
    modifiedTime CDATA #IMPLIED
    createdByUser CDATA #REQUIRED
    createdByName CDATA #IMPLIED
    createdTime CDATA #REQUIRED
    changeNote CDATA #REQUIRED
>
<!ELEMENT associateItem EMPTY>
<!ATTLIST associateItem
    type (cd | con | conte | cs | csi | de | dec | oc | prop | proto | pv | qc | qcm | qcq | qcv | vd | vm) #REQUIRED
    name CDATA #REQUIRED
    id ID #REQUIRED
    publicId CDATA #IMPLIED
    version CDATA #IMPLIED
    modifiedByUser CDATA #IMPLIED
    modifiedByName CDATA #IMPLIED
    modifiedTime CDATA #IMPLIED
    createdByUser CDATA #REQUIRED
    createdByName CDATA #IMPLIED
    createdTime CDATA #REQUIRED
    changeNote CDATA #REQUIRED
>
<!ELEMENT details (change+)>
<!ATTLIST details
    modifiedByUser CDATA #REQUIRED
    modifiedByName CDATA #REQUIRED
    time CDATA #REQUIRED
>
<!ELEMENT change EMPTY>
<!ATTLIST change
    attribute (ASL_NAME | BEGIN_DATE | CDE_ID | CDR_IDSEQ | CD_IDSEQ | CHANGE_NOTE | CONCAT_CHAR | CONDR_IDSEQ | CONTE_IDSEQ | CON_IDSEQ | CREATED_BY | CSTL_NAME | CRTL_NAME | CS_CSI_IDSEQ | CS_ID | C_DEC_IDSEQ | C_DE_IDSEQ | C_VD_IDSEQ | DATE_CREATED | DATE_MODIFIED | DCTL_NAME | DECIMAL_PLACE | DEC_ID | DEC_IDSEQ | DEC_REC_IDSEQ | DEFINITION_SOURCE | DELETED_IND | DESCRIPTION | DESIG_IDSEQ | DETL_NAME | DE_IDSEQ | DE_REC_IDSEQ | DISPLAY_ORDER | DOC_TEXT | DTL_NAME | END_DATE | FORML_NAME | HIGH_VALUE_NUM | LABEL_TYPE_FLAG | LAE_NAME | LATEST_VERSION_IND | LONG_NAME | LOW_VALUE_NUM | MAX_LENGTH_NUM | METHODS | MIN_LENGTH_NUM | MODIFIED_BY | NAME | OBJ_CLASS_QUALIFIER | OCL_NAME | OC_ID | OC_IDSEQ | ORIGIN | PREFERRED_DEFINITION | PREFERRED_NAME | PROPERTY_QUALIFIER | PROPL_NAME | PROP_ID | PROP_IDSEQ | PV_IDSEQ | P_DEC_IDSEQ | P_DE_IDSEQ | P_VD_IDSEQ | QUALIFIER_NAME | QUESTION | RDTL_NAME | RD_IDSEQ | REP_IDSEQ | RL_NAME | RULE | SHORT_MEANING | UOML_NAME | URL | VALUE | VD_ID | VD_IDSEQ | VD_REC_IDSEQ | VD_TYPE_FLAG | VERSION) #REQUIRED
    oldValue CDATA #IMPLIED
    newValue CDATA #IMPLIED
>

<!ELEMENT group (associate*)>
<!ATTLIST group
    changedItemId IDREF #REQUIRED
>
<!ELEMENT associate EMPTY>
<!ATTLIST associate
    childItemId IDREF #REQUIRED
    parentItemId IDREF #REQUIRED
>

=== CBIIT/cadsr-sentinel/sentinel/dtd/report.xml
<!-- This is an example for the cadsrsentinel*.dtd. The values contained below are NOT guaranteed
        to be valid.
-->

<!-- Identify the content as the NCI caDSR data
-->

<!DOCTYPE cadsr SYSTEM "cadsrsentinel-1.0.dtd">

<cadsr>
    <!-- Identify the Alert Report output.
    -->
    <alertReport softwareName="NCI caDSR Sentinel Report Generator" softwareVersion="3.2.0.2">

        <!-- Describe the database used as the source of the data.
        -->
        <database name="NCI caDSR DEV" rai="2.16.840.1.113883.3.26.2" server="CBDEV"/>

        <!-- Describe the Alert Definition
        -->
        <definition>

            <!-- Basics
            -->
            <name value="alert definition name" />
            <id>database id</id>
            <intro>introduction text</intro>
            <createdBy user="account" name="person" email="email address"/>
            <recipient user="account" name="person1" email="email address" />
            <recipient user="account" name="person2" email="email address" />
            <summary>descriptive text</summary>
            <criteria type="CONTE" value="database id" />
            <criteria type="CSI">
                <value>xxxx</value>
                <value>xxxx</value>
                <value>xxxx</value>
            </criteria>
            <monitor type="WFS" id="database id" />
            <monitor type="REG" id="database id" />
            <monitor type="VERS" value="2"/>

            <!-- Describe the reporting scedule
            -->
            <lastAutoRun time="date & time"/>
            <frequency unit="daily, weekly, monthly" value="1"/>
            <status code="active, inactive, run once, run dates" beginDate="date" endDate="date"/>

            <!-- Describe the report
            -->
            <level depth="###"/>
            <start date="date"/>
            <end date="date"/>
            <createdOn time="date & time"/>
        </definition>

        <!-- Describe each (Administered) Item on the report.
        -->
        <changedItem
            type="DE, DEC, VD, OC, etc"
            name="name at time of report creation"
            id="database id"
            publicId="public id if exists"
            version="version if exists"
            modifiedByUser="account"
            modifiedByName="person"
            modifiedTime="date & time"
            createdByUser="account"
            createdByName="person"
            createdTime="date & time"
            changeNote="text">
            <details modifiedByUser="user" time="date & time">
                <change attribute="xxx" oldValue="xxx" newValue="xxx" />
                <change attribute="xxx"><oldValue>xxx</oldValue><newValue>xxx</newValue></change>
                <change attribute="xxx" oldValue="xxx" newValue="xxx" />
            </details>
            <details modifiedByUser="user" time="date & time">
                <change attribute="xxx"><oldValue>xxx</oldValue><newValue>xxx</newValue></change>
                <change attribute="xxx" oldValue="xxx" newValue="xxx" />
                <change attribute="xxx" oldValue="xxx" newValue="xxx" />
            </details>
        </changedItem>

        <!-- The following may not be needed for the first implementation?
        -->
        <associateItem
            type="DE, DEC, VD, OC, etc"
            name="name at time of report creation"
            id="database id"
            publicId="public id if exists"
            version="version if exists"
            modifiedByUser="user"
            modifiedTime="date & time"
            createdByUser="name"
            createdTime="date & time"
            changeNote="text"/>
        <associateItem
            type="DE, DEC, VD, OC, etc"
            name="name at time of report creation"
            id="database id"
            publicId="public id if exists"
            version="version if exists"
            modifiedByUser="user"
            modifiedTime="date & time"
            createdByUser="name"
            createdTime="date & time"
            changeNote="text"/>
        <associateItem
            type="DE, DEC, VD, OC, etc"
            name="name at time of report creation"
            id="database id"
            publicId="public id if exists"
            version="version if exists"
            modifiedByUser="user"
            modifiedTime="date & time"
            createdByUser="name"
            createdTime="date & time"
            changeNote="text"/>
        <associateItem
            type="DE, DEC, VD, OC, etc"
            name="name at time of report creation"
            id="database id"
            publicId="public id if exists"
            version="version if exists"
            modifiedByUser="user"
            modifiedTime="date & time"
            createdByUser="name"
            createdTime="date & time"
            changeNote="text"/>

        <!-- Describe each group as associations between the items.
        -->
        <group changedItemId="database id">
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
        </group>
        <group changedItemId="database id">
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
        </group>
        <group changedItemId="database id">
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
            <associate childItemId="database id" parentItemId="database id" />
        </group>
    </alertReport>
</cadsr>
